#!/bin/sh

mkdir ex00
mkdir ex01
mkdir ex02
mkdir ex03
mkdir ex04
mkdir ex05
mkdir ex06
mkdir ex07
mkdir ex08
mkdir ex09
mkdir ex10

alias nnn="norminette -R CheckForbiddenSourceHeader"
alias ls='ls -F'
